

import Head from 'next/head';
import { useEffect } from 'react'
import HomePage from '../components/Homepage';

const Home = () => {
  
 

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        

      </Head>

<HomePage/>

   
      

    </div>
  );
};

export default Home;
