

import Head from 'next/head';
import { useEffect } from 'react'
import HomePage from '../components/Homepage';

const Home = () => {
  
 

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link href="https://www.db.onlinewebfonts.com/c/f96c2990a009f9c1b0745e68c4cac608?family=Eina" rel="stylesheet" type="text/css"/>

      </Head>

<HomePage/>

   
      

    </div>
  );
};

export default Home;
